### ISSUE TITLE
Implement nitrogen's sync_panel

### ISSUE THREAD

**Issue by rgrinberg** [5HT/n2o#205]
Reading this blog post http://sigma-star.com/blog/post/sync_panel I thought it was pretty cool. Does it make sense to have this in n2o as well?

**Comment by 5HT** [comment]
Funny, seems on https://www.youtube.com/watch?v=eECzZTrn8ms&t=647 it stucked, and Jessy refreshed the page :-)

This element is impressive to newbies but not for guys who writing N2O in production.
Anyway most of our application support dynamic auto changing. This is about how many existed web pages should receive notification about update: ALL, SOME or NONE. Because syncing ALL pages would create a storm, and for SOME case you should provide your own PubSub subscription mesh. So anyway having separated control is good for demo, not for N2O core. If you want to can provide #sync_panel example in N2O easily.
